openapi: 3.0.0
info:
  title:  PLURAL
  description: Pakedge LUa Rest Api Library
  version: "2"
  contact:
    name: API Support
    email: lvasiljevic@control4.com
    url: https://www.control4.com/
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://localhost:3001
paths:
  /network:
    get:
      operationId: network
      responses:
        '200':
          description: something to say about get /network
          content:
            application/json:
              schema:
                $ref: './content/wr1/v2/response/network/network.yaml'
        '404':
          description: Not Found
          content:
            application/xml:
              schema:
                $ref: './content/wr1/v2/response/404.yaml'
  /network/wans:
    get:
      operationId: networkWans
      responses:
        '200':
          description: "all wans port ond device"
          content:
            application/json:
              schema:
                $ref: './content/wr1/v2/response/network/wans.yaml'
  /network/wans/{wanId}:
    parameters:
      - in: path
        name: wanId
        required: true
        schema:
          type: integer
    get:
      operationId: get_network_wan_id
      summary: Gets a wan by ID
      responses:
        '200':
          description: "wan port settings of id"
          content:
            application/json:
              schema:
                $ref: './content/wr1/v2/response/network/wan.yaml'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: './content/wr1/v2/response/404.yaml'
    put:
      operationId: put_network_wan_id
      requestBody:
        content:
          application/json:
            schema:
              $ref: './content/wr1/v2/request/network/wan.yaml'
      responses:
        '200':
          description: 'Return standard success response'
          content:
            application/json:
              schema:
                $ref: './content/wr1/v2/response/200.yaml'
        '404':
          description: Not Found
          content:
            application/xml:
              schema:
                $ref: './content/wr1/v2/response/404.yaml'
  /network/wans/{wanId}/ipv4:
    parameters:
      - in: path
        name: wanId
        required: true
        schema:
          type: integer
    get:
      operationId: get_network_wan_id_ipv4
      summary: Gets a wan ipv4 of ID
      responses:
        '200':
          description: "wan ipv4 settings of id"
          content:
            application/json:
              schema:
                $ref: './content/wr1/v2/response/network/wanipv4.yaml'
    put:
      operationId: put_network_wan_id_ipv4
      requestBody:
        content:
          application/json:
            schema:
              $ref: './content/wr1/v2/request/network/wanipv4.yaml'
      responses:
        '200':
          description: 'Return standard success response'
          content:
            application/json:
              schema:
                $ref: './content/wr1/v2/response/200.yaml'
