openapi: 3.0.0
info:
  title:  PLURAL
  description: Pakedge LUa Rest Api Library
  version: "1"
  contact:
    name: API Support
    email: lvasiljevic@control4.com
    url: https://www.control4.com/
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://localhost:3001
paths:
  /leds:
    get:
      operationId: leds
      responses:
        '200':
          description: Turn on/off leds on device
          content:
            application/json:
              schema:
                $ref: './content/wr1/v1/response/leds.yaml'
    post:
      requestBody:
        description: 'Change leds status'
        required: true
        content:
          application/json:
            schema:
              $ref: './content/wr1/v1/request/leds.yaml'
      responses:
        '200':
          description: Successful set new state of leds
          content:
            application/json:
              schema:
                $ref: './content/wr1/v1/response/200.yaml'

