openapi: 3.0.0
info:
  title:  PLURAL
  description: Pakedge LUa Rest Api Library
  version: "2"
  contact:
    name: API Support
    email: lvasiljevic@control4.com
    url: https://www.control4.com/
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://localhost:3001/api/v2
tags:
  - name: network
    description: API for network
paths:
  $ref: "./content/wr1/v2/paths/wr1_index.yaml"
components:
  securitySchemes:
    $ref: "./content/common/v1/security/bearer-auth.yaml"
  schemas:
    $ref: "./content/wr1/v2/schemas/wr1_index.yaml"
  responses:
    $ref: "./content/wr1/v2/response/wr1_index.yaml"
  parameters:
    $ref: "./content/wr1/v2/parameters/wr1_index.yaml"
  requestBodies:
    $ref: "./content/wr1/v2/request/wr1_index.yaml"
x-basePath: '{domain}/api/v{version}'