openapi: 3.0.0
info:
  title:  PLURAL
  description: Pakedge Lua Rest Api Library
  version: "1"
  contact:
    name: API Support
    email: lvasiljevic@control4.com
    url: https://www.control4.com/
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://localhost:3001/api/v1
tags:
  - name: auth
    description: API for authentication
  - name: leds
    description: API for leds
paths:
  $ref: "./content/PakedgeWR-1/v1/paths/PakedgeWR-1_index.yaml"
components:
  securitySchemes:
    $ref: "./content/common/v1/security/bearer-auth.yaml"
  schemas:
    $ref: "./content/PakedgeWR-1/v1/schemas/PakedgeWR-1_index.yaml"
  responses:
    $ref: "./content/PakedgeWR-1/v1/response/PakedgeWR-1_index.yaml"
  requestBodies:
    $ref: "./content/PakedgeWR-1/v1/request/PakedgeWR-1_index.yaml"

